apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "100Mi"
        cpu: "300m"
      limits:
        memory: "100Mi"
        cpu: "300m"
